name: subx
version: 0.3.0
description: RxDart Subscriptions management
author: Tyrcord Inc. <dev@tyrcord.com>
homepage: https://github.com/tyrcord/subx
issue_tracker: https://github.com/tyrcord/subx/issues

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  async: ^2.2.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.3
  rxdart: ^0.22.0
