name: subx
version: 1.0.0
description: >
  RxDart Subscriptions management.
  Provide Apis to store and manage RxDart subscriptions
  and provide methods to unsubscribe them all.
homepage: https://github.com/tyrcord/subx
issue_tracker: https://github.com/tyrcord/subx/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.5.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  rxdart: ^0.26.0
  dart_code_metrics: ^3.0.0
