name: subx
version: 1.0.3
description: >
  RxDart Subscriptions management.
  Provide Apis to store and manage RxDart subscriptions
  and provide methods to unsubscribe them all.
homepage: https://github.com/tyrcord/subx
issue_tracker: https://github.com/tyrcord/subx/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.16.8
  rxdart: ^0.27.1
  dart_code_metrics: ^4.0.1
