name: subx
version: 0.6.2
description: >
  RxDart Subscriptions management.
  Provide Apis to store and manage RxDart subscriptions
  and provide methods to unsubscribe them all.
homepage: https://github.com/tyrcord/subx
issue_tracker: https://github.com/tyrcord/subx/issues

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  async: ^2.4.2

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
  rxdart: ^0.24.1
  dart_code_metrics: ^2.3.1
