name: subx
version: 1.0.2
description: >
  RxDart Subscriptions management.
  Provide Apis to store and manage RxDart subscriptions
  and provide methods to unsubscribe them all.
homepage: https://github.com/tyrcord/subx
issue_tracker: https://github.com/tyrcord/subx/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.7.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9
  rxdart: ^0.27.1
  dart_code_metrics: ^4.0.1
